import { z } from "zod";

const color = z.string().regex(/^#[0-9a-f]{6}$/i);
const gradientStop = z.object({
  color,
  pos: z.number().min(0).max(100),
});
const animationName = z.enum([
  "none",
  "pulse",
  "breathe",
  "heartbeat",
  "float",
  "bounce",
  "swing",
  "shake",
  "wobble",
  "jump",
  "wave",
  "ripple",
  "flip_x",
  "flip_y",
  "squeeze",
  "spin",
  "roll",
  "glitch",
  "hue_rotate",
  "disco",
  "neon_flicker",
  "zoom_in",
  "letter_spin",
  "letter_swing",
  "letter_bounce",
  "letter_scale",
  "letter_shake",
  "letter_orbit",
  "shine",
]);
export const buttonIconNames = [
  "none",
  "custom",
  "play",
  "heart",
  "check",
  "arrow",
  "star",
  "plus",
  "minus",
  "close",
  "dot",
  "circle",
  "square",
  "diamond",
  "triangle",
  "bolt",
  "music",
  "phone",
  "mail",
  "search",
  "home",
  "user",
  "lock",
  "unlock",
  "bell",
  "flag",
  "bookmark",
  "calendar",
  "clock",
  "camera",
  "image",
  "link",
  "globe",
  "gear",
  "cloud",
  "download",
  "upload",
  "share",
  "send",
  "pencil",
  "trash",
  "cart",
  "gift",
  "coffee",
  "flame",
  "leaf",
  "sun",
  "moon",
  "snowflake",
  "rocket",
  "sparkles",
  "smile",
  "warning",
  "info",
  "question",
  "location",
  "eye",
] as const;
export type ButtonIcon = (typeof buttonIconNames)[number];
export const buttonIcons: {
  value: ButtonIcon;
  label: string;
  glyph: string;
}[] = [
  ["none", "None", "×"],
  ["play", "Play", "▶"],
  ["heart", "Heart", "♥"],
  ["check", "Check", "✓"],
  ["arrow", "Arrow", "→"],
  ["star", "Star", "★"],
  ["plus", "Plus", "+"],
  ["minus", "Minus", "−"],
  ["close", "Close", "×"],
  ["dot", "Dot", "•"],
  ["circle", "Circle", "●"],
  ["square", "Square", "■"],
  ["diamond", "Diamond", "◆"],
  ["triangle", "Triangle", "▲"],
  ["bolt", "Bolt", "⚡"],
  ["music", "Music", "♪"],
  ["phone", "Phone", "☎"],
  ["mail", "Mail", "✉"],
  ["search", "Search", "⌕"],
  ["home", "Home", "⌂"],
  ["user", "User", "♙"],
  ["lock", "Lock", "⌑"],
  ["unlock", "Unlock", "⌗"],
  ["bell", "Bell", "♢"],
  ["flag", "Flag", "⚑"],
  ["bookmark", "Bookmark", "▮"],
  ["calendar", "Calendar", "▦"],
  ["clock", "Clock", "◷"],
  ["camera", "Camera", "▣"],
  ["image", "Image", "▧"],
  ["link", "Link", "🔗"],
  ["globe", "Globe", "⊕"],
  ["gear", "Gear", "⚙"],
  ["cloud", "Cloud", "☁"],
  ["download", "Download", "⇩"],
  ["upload", "Upload", "⇧"],
  ["share", "Share", "↗"],
  ["send", "Send", "➤"],
  ["pencil", "Pencil", "✎"],
  ["trash", "Trash", "♲"],
  ["cart", "Cart", "▱"],
  ["gift", "Gift", "✚"],
  ["coffee", "Coffee", "◒"],
  ["flame", "Flame", "♨"],
  ["leaf", "Leaf", "❧"],
  ["sun", "Sun", "☀"],
  ["moon", "Moon", "☾"],
  ["snowflake", "Snowflake", "❄"],
  ["rocket", "Rocket", "➶"],
  ["sparkles", "Sparkles", "✦"],
  ["smile", "Smile", "☺"],
  ["warning", "Warning", "⚠"],
  ["info", "Info", "ⓘ"],
  ["question", "Question", "?"],
  ["location", "Location", "⌖"],
  ["eye", "Eye", "◉"],
].map(([value, label, glyph]) => ({
  value: value as ButtonIcon,
  label,
  glyph,
}));

export const buttonStateSchema = z.object({
  text: z.string().max(2000),
  icon: z.enum(buttonIconNames).default("none"),
  iconDataUrl: z.string().max(4100000).optional(),
  iconPosition: z.enum(["left", "right"]).default("left"),
  iconSize: z.number().min(10).max(120).default(22),
  iconGap: z.number().min(0).max(40).default(10),
  iconColor: color.default("#ffffff"),
  fontFamily: z.string().max(80),
  fontBase64: z.string().max(4100000).optional(),
  fontAssetId: z.string().uuid().optional(),
  fontSize: z.number().min(10).max(120),
  fontWeight: z.number().min(300).max(900),
  letterSpacing: z.number().min(-20).max(60),
  lineHeight: z.number().min(0.5).max(2.5).default(1.5),
  rotation: z.number().min(-180).max(180).default(0),
  curve: z.number().min(-100).max(100).default(0),
  zigzag: z.number().min(-100).max(100).default(0),
  wave: z.number().min(0).max(100).default(0),
  align: z.enum(["left", "center", "right"]).default("center"),
  isItalic: z.boolean().default(false),
  isUnderline: z.boolean().default(false),
  paddingX: z.number().min(0).max(100),
  paddingY: z.number().min(0).max(60),
  radius: z.number().min(0).max(100),
  borderWidth: z.number().min(0).max(20),
  borderColor: color,
  textColor: color,
  textFillType: z.enum(["solid", "gradient", "radial"]).default("solid"),
  textStops: z
    .array(gradientStop)
    .min(2)
    .max(12)
    .default([
      { color: "#ff0000", pos: 0 },
      { color: "#0000ff", pos: 100 },
    ]),
  textAngle: z.number().min(0).max(360).default(90),
  textOpacity: z.number().min(0).max(1).default(1),
  fillType: z.enum(["solid", "gradient", "radial"]),
  fillStart: color,
  fillEnd: color,
  fillOpacity: z.number().min(0).max(1).default(1),
  fillStops: z
    .array(gradientStop)
    .min(2)
    .max(12)
    .default([
      { color: "#f47757", pos: 0 },
      { color: "#c94d38", pos: 100 },
    ]),
  fillAngle: z.number().min(0).max(360),
  shadowEnabled: z.boolean(),
  shadowColor: color,
  shadowOpacity: z.number().min(0).max(1),
  shadowBlur: z.number().min(0).max(80),
  shadowX: z.number().min(-50).max(50),
  shadowY: z.number().min(-50).max(50),
  hoverFill: color,
  hoverText: color,
  hoverLift: z.number().min(0).max(20),
  animation: animationName,
  wholeAnimation: animationName.optional(),
  textAnimation: animationName.optional(),
  animationSpeed: z.number().min(0.2).max(4),
  background: color,
  backgroundOpacity: z.number().min(0).max(1).default(1),
  backgroundTransparent: z.boolean().default(true),
  backgroundType: z
    .enum(["transparent", "solid", "gradient", "radial"])
    .optional(),
  backgroundEnd: color.optional(),
  backgroundStops: z.array(gradientStop).min(2).max(12).optional(),
  backgroundAngle: z.number().min(0).max(360).optional(),
});

export type ButtonState = z.infer<typeof buttonStateSchema>;

export const defaultButtonState: ButtonState = {
  text: "GET STARTED",
  icon: "none",
  iconPosition: "left",
  iconSize: 22,
  iconGap: 10,
  iconColor: "#ffffff",
  fontFamily: "Inter",
  fontSize: 22,
  fontWeight: 700,
  letterSpacing: 0.4,
  lineHeight: 1.5,
  rotation: 0,
  curve: 0,
  zigzag: 0,
  wave: 0,
  align: "center",
  isItalic: false,
  isUnderline: false,
  paddingX: 34,
  paddingY: 16,
  radius: 10,
  borderWidth: 0,
  borderColor: "#c95438",
  textColor: "#ffffff",
  textFillType: "solid",
  textStops: [
    { color: "#ff0000", pos: 0 },
    { color: "#0000ff", pos: 100 },
  ],
  textAngle: 90,
  textOpacity: 1,
  fillType: "gradient",
  fillStart: "#f47757",
  fillEnd: "#c94d38",
  fillOpacity: 1,
  fillStops: [
    { color: "#f47757", pos: 0 },
    { color: "#c94d38", pos: 100 },
  ],
  fillAngle: 135,
  shadowEnabled: true,
  shadowColor: "#9d3b2d",
  shadowOpacity: 0.24,
  shadowBlur: 20,
  shadowX: 0,
  shadowY: 8,
  hoverFill: "#b94031",
  hoverText: "#ffffff",
  hoverLift: 4,
  animation: "none",
  wholeAnimation: "none",
  textAnimation: "none",
  animationSpeed: 1,
  background: "#f4f5f6",
  backgroundOpacity: 1,
  backgroundTransparent: true,
  backgroundType: "transparent",
  backgroundEnd: "#d6e9ef",
  backgroundStops: [
    { color: "#f4f5f6", pos: 0 },
    { color: "#d6e9ef", pos: 100 },
  ],
  backgroundAngle: 135,
};
