import type { EditorState, Fill, Settings, Plan } from "./types";
export const baseFill: Fill = {
  type: "solid",
  color: "#fc7946",
  opacity: 1,
  angle: 90,
  stops: [
    { color: "#ffd16b", pos: 0 },
    { color: "#fb6938", pos: 100 },
  ],
  colors: ["#ffc348", "#43c6ab", "#8865cc", "#ee678c"],
  altMode: "solid",
  altScope: "letter",
  scope: "text",
  altGradients: [{ c1: "#facc15", c2: "#f97316", angle: 90 }],
  patternSize: 100,
  patternBgType: "none",
  patternBgColor: "#ffffff",
  patternBgStops: [
    { color: "#ffffff", pos: 0 },
    { color: "#000000", pos: 100 },
  ],
  patternBgAngle: 90,
  altImages: [],
};
export const defaultState: EditorState = {
  text: "CREATE",
  fontFamily: "Bungee",
  letterSpacing: 0,
  lineHeight: 1.1,
  align: "center",
  isBold: true,
  isItalic: false,
  isUnderline: false,
  rotation: -5,
  curve: 0,
  zigzag: 0,
  wave: 0,
  animation: { id: "none", speed: 1 },
  fill: { ...baseFill, type: "gradient" },
  layers: [
    {
      ...baseFill,
      id: 1,
      layerType: "3d",
      enabled: true,
      color: "#bd4028",
      size: 16,
      width: 0,
      angle: 110,
    },
  ],
  bg: { ...baseFill, type: "solid", color: "#ffeedc", base64: null },
};
export const defaultSettings: Settings = {
  site_name: "EXCPIX",
  description:
    "Create something unmistakably yours. 3D text, AI design and design resources.",
  header_links: [
    { label: "Graffiti Text", href: "/search/graffiti" },
    { label: "Golden Text", href: "/search/gold" },
    { label: "Neon Text", href: "/search/neon" },
    { label: "3D Alphabet", href: "/ai" },
  ],
  categories: [
    { id: "3d-text", name: "3D Text" },
    { id: "ai", name: "AI Design" },
    { id: "design", name: "Design" },
    { id: "text", name: "Text" },
    { id: "visual", name: "Visual" },
  ],
  badges: ["ABC", "NEW", "PRO", "3D", "AI", ""],
  ads_enabled: false,
  ad_client: "",
  ad_slots: [],
  ad_disabled_pages: ["/login", "/pricing", "/owner", "/admin"],
  maintenance: false,
  announcement: "",
  free_download_limit: 5,
  watermark: "EXCPIX",
  social_handle: "@excpix",
  billing_periods: ["monthly", "yearly"],
  footer_description: "Make type that feels unmistakably yours.",
  footer_columns: [
    {
      title: "Explore",
      links: [
        { label: "3D Text", href: "/3d-text" },
        { label: "AI Design", href: "/ai" },
        { label: "Design", href: "/design" },
        { label: "Visual", href: "/visual" },
      ],
    },
    {
      title: "Resources",
      links: [
        { label: "About", href: "/about" },
        { label: "FAQ", href: "/faq" },
        { label: "Contact", href: "/contact" },
      ],
    },
    {
      title: "Legal",
      links: [
        { label: "Privacy", href: "/privacy" },
        { label: "Terms", href: "/term" },
        { label: "Refunds", href: "/return-policy" },
      ],
    },
  ],
  footer_copyright: "All rights reserved.",
  footer_tagline: "Built for better lettering.",
};
export const defaultPlans: Plan[] = [
  {
    id: "free",
    name: "Free",
    price: 0,
    yearly_price: 0,
    currency: "INR",
    download_limit: 5,
    max_quality: 1280,
    features: [
      "5 downloads per day",
      "Free styles",
      "Standard PNG exports",
      "Personal saved collection",
    ],
    active: true,
  },
  {
    id: "pro",
    name: "Pro",
    price: 699,
    yearly_price: 6990,
    currency: "INR",
    regional_prices: [
      {
        country: "",
        currency: "EUR",
        price: 10,
        yearly_price: 100,
        active: true,
        gateways: ["stripe"],
      },
      {
        country: "",
        currency: "JPY",
        price: 1800,
        yearly_price: 18000,
        active: true,
        gateways: ["stripe"],
      },
      {
        country: "",
        currency: "GBP",
        price: 9,
        yearly_price: 90,
        active: true,
        gateways: ["stripe"],
      },
      {
        country: "",
        currency: "AUD",
        price: 18,
        yearly_price: 180,
        active: true,
        gateways: ["stripe"],
      },
      {
        country: "",
        currency: "CAD",
        price: 18,
        yearly_price: 180,
        active: true,
        gateways: ["stripe"],
      },
      {
        country: "",
        currency: "CHF",
        price: 10,
        yearly_price: 100,
        active: true,
        gateways: ["stripe"],
      },
      {
        country: "",
        currency: "CNY",
        price: 90,
        yearly_price: 900,
        active: true,
        gateways: ["stripe"],
      },
      {
        country: "",
        currency: "AED",
        price: 45,
        yearly_price: 450,
        active: true,
        gateways: ["stripe"],
      },
    ],
    download_limit: 100,
    max_quality: 7680,
    features: [
      "100 downloads per day",
      "All premium styles",
      "4K and 8K PNG exports",
      "Animated GIF exports",
      "No watermark or ads",
    ],
    active: true,
  },
  {
    id: "studio",
    name: "Studio",
    price: 2097,
    yearly_price: 20970,
    currency: "INR",
    regional_prices: [
      {
        country: "",
        currency: "EUR",
        price: 30,
        yearly_price: 300,
        active: true,
        gateways: ["stripe"],
      },
      {
        country: "",
        currency: "JPY",
        price: 5400,
        yearly_price: 54000,
        active: true,
        gateways: ["stripe"],
      },
      {
        country: "",
        currency: "GBP",
        price: 27,
        yearly_price: 270,
        active: true,
        gateways: ["stripe"],
      },
      {
        country: "",
        currency: "AUD",
        price: 54,
        yearly_price: 540,
        active: true,
        gateways: ["stripe"],
      },
      {
        country: "",
        currency: "CAD",
        price: 54,
        yearly_price: 540,
        active: true,
        gateways: ["stripe"],
      },
      {
        country: "",
        currency: "CHF",
        price: 30,
        yearly_price: 300,
        active: true,
        gateways: ["stripe"],
      },
      {
        country: "",
        currency: "CNY",
        price: 270,
        yearly_price: 2700,
        active: true,
        gateways: ["stripe"],
      },
      {
        country: "",
        currency: "AED",
        price: 135,
        yearly_price: 1350,
        active: true,
        gateways: ["stripe"],
      },
    ],
    download_limit: 1000,
    max_quality: 8192,
    features: [
      "1,000 downloads per day",
      "Everything in Pro",
      "MAX resolution exports",
      "Private saved projects",
      "Priority support",
    ],
    active: true,
  },
];
export const catalogSeeds = [
  [
    "sunset-pop",
    "Sunset Pop",
    "3d-text",
    "CREATE",
    "Bungee",
    "#ffc85b",
    "#ff713c",
    "#aa3b27",
    "#ffead9",
    "3D",
    "retro",
  ],
  [
    "electric-chrome",
    "Electric Chrome",
    "3d-text",
    "CHROME",
    "Bungee",
    "#ffffff",
    "#80b5d4",
    "#283e55",
    "#142d36",
    "PRO",
    "chrome",
  ],
  [
    "pink-daydream",
    "Pink Daydream",
    "3d-text",
    "Sweet",
    "Pacifico",
    "#ffe2ee",
    "#f97dab",
    "#b03b75",
    "#f9d9e8",
    "NEW",
    "pink",
  ],
  [
    "wild-style",
    "Wild Style",
    "3d-text",
    "FRESH",
    "Bangers",
    "#d6fe42",
    "#97d522",
    "#2a651c",
    "#244d34",
    "ABC",
    "graffiti",
  ],
  [
    "liquid-gold",
    "Liquid Gold",
    "ai",
    "GOLD",
    "Bungee",
    "#fff2a3",
    "#d59f25",
    "#7a4713",
    "#272521",
    "PRO",
    "gold",
  ],
  [
    "ocean-blue",
    "Ocean Blue",
    "ai",
    "OCEAN",
    "Bungee",
    "#c3fafa",
    "#36b8da",
    "#076689",
    "#d4f1f3",
    "AI",
    "ocean",
  ],
  [
    "bold-perspective",
    "Bold Perspective",
    "design",
    "MAKE\nWAVES",
    "Bungee",
    "#ffb198",
    "#ff6959",
    "#b72f42",
    "#f95f53",
    "NEW",
    "poster",
  ],
  [
    "lavender-dream",
    "Lavender Dream",
    "3d-text",
    "Dream",
    "Pacifico",
    "#faf1ff",
    "#b799f3",
    "#7460a6",
    "#e9e2f5",
    "",
    "pastel",
  ],
  [
    "neon-nights",
    "Neon Nights",
    "3d-text",
    "NEON",
    "Bangers",
    "#c8ffac",
    "#46ef87",
    "#128b76",
    "#172b2c",
    "PRO",
    "neon",
  ],
  [
    "retro-summer",
    "Retro Summer",
    "design",
    "SUMMER",
    "Bangers",
    "#fdf0ca",
    "#ffd073",
    "#bd5d4a",
    "#8cbfbc",
    "NEW",
    "retro",
  ],
  [
    "bubble-gum",
    "Bubble Gum",
    "ai",
    "POP!",
    "Bungee",
    "#ffcede",
    "#f679bc",
    "#a64175",
    "#ffdfea",
    "ABC",
    "bubble",
  ],
  [
    "candy-colors",
    "Candy Colors",
    "3d-text",
    "2025",
    "Bungee",
    "#ffc145",
    "#38c6af",
    "#945d2e",
    "#f4f2f0",
    "ABC",
    "colorful",
  ],
  [
    "midnight-type",
    "Midnight Type",
    "design",
    "AFTER\nHOURS",
    "Bangers",
    "#fafafa",
    "#aaaaaa",
    "#444444",
    "#222222",
    "PRO",
    "minimal",
  ],
  [
    "mint-condition",
    "Mint Condition",
    "3d-text",
    "MINT",
    "Bungee",
    "#d6ffcc",
    "#82dcae",
    "#389786",
    "#e0f5ea",
    "",
    "pastel",
  ],
  [
    "red-hot",
    "Red Hot",
    "ai",
    "FIRE",
    "Bangers",
    "#fff6ac",
    "#ff7435",
    "#b52725",
    "#ffdbbb",
    "PRO",
    "fire",
  ],
  [
    "soft-shadows",
    "Soft Shadows",
    "3d-text",
    "hello",
    "Pacifico",
    "#ffffff",
    "#ececec",
    "#b6b9c3",
    "#e5e7ec",
    "",
    "minimal",
  ],
];
